name: compile sonar-netcd4 into PDF

on: 
  push:
    paths:
      - 'SONAR-netCDF4/docs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # comment XX
      - uses: actions/checkout@v2
      - uses: mgred/asciidoctor-action@master
        with:
          args: asciidoctor crr341.adoc
